const organizerRoutes={
    organizerSignup:'/organizer/register',
    organizerLogin:'/organizer/login',
    otpSenting:'/organizer/sentOtp',
    verifyOtp:'/organizer/verifyotp',
    logout:'/organizer/logout',
    approve:'/organizer/approvel',
    profile :'/organizer/profile',
    uploadBackground:'/organizer/backgroundUpload',
    uploadProfilePicture:'/organizer/profilePicture',
    resendOtp:"/organizer/resendOtp",
    getEvents:'/organizer/getEvents',
    allcategory :"/organizer/allcategory",
    profileEdit:"/organizer/profileEdit",
    eventCategory:"/organizer/categorys",
    eventCreation:"/organizer/eventCreation",
    getAllEvents:"/organizer/getAllEvents",
    getEventDetails:'/organizer/eventDetails',
    postEvent:"/organizer/eventPost",
    eventPosts :"/organizer/alleventPost",
    getUpcomingEvent:"/organizer/getUpcomingEvent",
    changeStatus:"/organizer/changeStatus",
    cancelEvent:"/organizer/cancel",
    getEventPostWithId:"/organizer/getOrganizerEventPost",
    updatePost:"/organizer/updatePost",
    getBooking:"/organizer/geAllbookings",
    updateEvent:"/organizer/updateEvent",
    getAllRequests:"/organizer/getRequests",
    getRequestDetails:"/organizer/getRequestDetails",
    approveRequest:"/organizer/approveRequest",
    rejectRequest:"/organizer/rejectRequest",
    requestEventCreat:"/organizer/requestEventCreation",
    getUserChat:"/organizer/chatList",
    postCreate:"/organizer/postCreate",
    postUpdate:"/organizer/postUpdate",
    postDelete:"/organizer/deletePost",
    getPosts:"/organizer/getPosts",
    getDashboardData:'/organizer/getDashboardData',
    getRevenue:"/organizer/getRevenue",
    getEventGraph:"/organizer/getEventGraph"
    
}

export default organizerRoutes